#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)
sudo apt-get update
sudo apt-get install -y nginx 
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
