#!/usr/bin/env bash
# Configure Nginx that HTTP response contains a custom header.
# Installs Nginx with the following configurations.

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html
sudo echo "Hello World" > /var/www/html/index.html
sudo echo "page not found" > /var/www/html/404.html

sudo echo "server {
    listen 80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html;
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-enabled/default

sudo service nginx restart
