#!/usr/bin/env bash
# Installs and configure HAProxy:
# Distributes requests using a round-robin algorithm.

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 187093-web-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 187093-web-02 100.25.103.162:80 check\n\tserver 187093-web-01 18.214.88.235:80  check" /etc/haproxy/haproxy.cfg
# sudo service haproxy start
sudo /etc/init.d/haproxy start
